const QA_HOST='cutover-legacy-routing-previ.northedge-website.pages.dev';
const QA_KEY='2026-08-09-cutover-r1-final';
const PREFIX='qa-northedge-preview-';
const H={'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','X-Robots-Tag':'noindex, nofollow'};
const json=(b,s=200)=>Response.json(b,{status:s,headers:H});
const allowed=u=>u.hostname===QA_HOST&&u.searchParams.get('qa')===QA_KEY;
async function state(env){const r=await env.LEADS_DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name IN ('leads','lead_rate_limits') ORDER BY name").all();const names=(r.results||[]).map(x=>x.name);const c=await env.LEADS_DB.prepare('SELECT COUNT(*) AS n FROM leads').first();return {tables:names,leadCount:Number(c?.n||0),schemaHealthy:names.includes('leads')&&names.includes('lead_rate_limits')}}
export async function onRequestGet({request,env}){const u=new URL(request.url);if(!allowed(u))return json({ok:false},404);if(!env.LEADS_DB)return json({ok:false,error:'LEADS_DB not bound'},503);try{const a=u.searchParams.get('action')||'state';if(a==='state'){const s=await state(env);return json({ok:s.schemaHealthy,...s})}if(a==='batch'){const b=(u.searchParams.get('batch')||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80);if(!b)return json({ok:false},400);const p=`${PREFIX}${b}-%@example.com`;const rows=await env.LEADS_DB.prepare('SELECT form_type, COUNT(*) AS n FROM leads WHERE email LIKE ? GROUP BY form_type ORDER BY form_type').bind(p).all();const c=await env.LEADS_DB.prepare('SELECT COUNT(*) AS n FROM leads WHERE email LIKE ?').bind(p).first();return json({ok:true,batch:b,total:Number(c?.n||0),forms:(rows.results||[]).map(r=>({form:r.form_type,count:Number(r.n||0)}))})}return json({ok:false},400)}catch(e){return json({ok:false,errorClass:e?.name||'DatabaseError'},500)}}
export async function onRequestPost({request,env}){const u=new URL(request.url);if(!allowed(u))return json({ok:false},404);if(!env.LEADS_DB)return json({ok:false},503);try{if(u.searchParams.get('action')!=='cleanup')return json({ok:false},400);const b=(u.searchParams.get('batch')||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80);if(!b)return json({ok:false},400);const p=`${PREFIX}${b}-%@example.com`;const before=await env.LEADS_DB.prepare('SELECT COUNT(*) AS n FROM leads WHERE email LIKE ?').bind(p).first();await env.LEADS_DB.prepare('DELETE FROM leads WHERE email LIKE ?').bind(p).run();const after=await env.LEADS_DB.prepare('SELECT COUNT(*) AS n FROM leads WHERE email LIKE ?').bind(p).first();return json({ok:Number(after?.n||0)===0,batch:b,deleted:Number(before?.n||0),remaining:Number(after?.n||0)})}catch(e){return json({ok:false,errorClass:e?.name||'DatabaseError'},500)}}
export function onRequest(){return json({ok:false},405)}
